apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  labels:
    app: ic-webapp
    env: prod
  namespace : icgroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: webapp
        image: ic-webapp:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ODOO_URL
          value: http://192.168.56.10:30008/
        - name: PGADMIN_URL
          value: http://192.168.56.10:30200/
---
apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-deployment
  namespace : icgroup
  labels:
    app: ic-webapp
    env: prod
   
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30002
  type: NodePort
  selector:
   app: ic-webapp
   