apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels: 
    app: pgadmin
    env: prod
  namespace: icgroup
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin4
        image: dpage/pgadmin4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@admin.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin-secret
              key: pgadmin-default-password
        ports:
        - containerPort: 5050
          name: postgres
        volumeMounts:
        - name: pg-admin-server
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
        - name: pg-admin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pg-admin-server
        configMap:
          name: pgadmin-config
          items:
          - key: servers.json
            path: servers.json    
      - name: pg-admin-data
        persistentVolumeClaim:
          claimName: pgadmin-pvc
  
---
apiVersion: v1
kind: Service
metadata:
  namespace: icgroup
  name: pgadmin
  labels:
    app: pgadmin
spec:
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 80
    nodePort: 30200
  type: NodePort
  selector:
   app: pgadmin