apiVersion: apps/v1
kind: Deployment
metadata:
  namespace : icgroup
  name: postgres
  labels:
    app: postgres
    env: prod
spec:
  selector:
   matchLabels:
    app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          ports:
          - containerPort: 5432
            name: postgres
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
      volumes:
      - name: postgredb
        hostPath:
          path: /data1/postgres
---
apiVersion: v1
kind: Service
metadata:
  namespace : icgroup
  name: postgres
  labels:
    app: postgres
    env: prod
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres